import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { registryComponents } from "../src/data/component-registry";

const schema = "https://ui.shadcn.com/schema/registry.json";
const itemSchema = "https://ui.shadcn.com/schema/registry-item.json";
const outputDir = path.resolve("public/r");
const sourceModulePath = path.resolve("src/registry/generated-sources.ts");
const site = "https://motion-lexicon.pages.dev";

await mkdir(outputDir, { recursive: true });

const items = await Promise.all(registryComponents.map(async (entry) => {
  const sourcePath = `src/registry/components/${entry.id}.tsx`;
  const source = await readFile(sourcePath, "utf8");
  const meta = {
    name: entry.id,
    type: "registry:ui" as const,
    title: entry.name.en,
    description: entry.description.en,
    dependencies: ["motion"],
    categories: [entry.category],
    docs: `${site}/en/components/${entry.id}/`,
    files: [{
      path: sourcePath,
      type: "registry:ui" as const,
      target: `components/motion-lexicon/${entry.id}.tsx`
    }]
  };

  await writeFile(
    path.join(outputDir, `${entry.id}.json`),
    `${JSON.stringify({
      $schema: itemSchema,
      ...meta,
      files: [{ ...meta.files[0], content: source }]
    }, null, 2)}\n`,
    "utf8"
  );

  return meta;
}));

const sourceEntries = await Promise.all(registryComponents.map(async (entry) => [
  entry.id,
  await readFile(`src/registry/components/${entry.id}.tsx`, "utf8")
] as const));

await writeFile(
  sourceModulePath,
  `// Generated by scripts/generate-registry.ts.\nexport const registrySources: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(sourceEntries), null, 2)};\n`,
  "utf8"
);

await writeFile(
  path.join(outputDir, "registry.json"),
  `${JSON.stringify({
    $schema: schema,
    name: "motion-lexicon",
    homepage: site,
    items
  }, null, 2)}\n`,
  "utf8"
);

console.log(`Registry generated: ${items.length} components`);
